# Assignment #2

# 1. Numpy basics (10 points)

**1.1** Import numpy as np into the Jupyter Notebook

In [76]:
import numpy as np

**1.2** Print out the methods and variables associated with the module numpy. 

In [77]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

## 2. Arrays (15 points)

**2.1** Create an evenly spaced 1D array of latitude values starting at -90.0 degrees and ending at 90.0 degrees with a pixel size of 1.0 degree [Hint: Use np.linspace()]. 

In [78]:
np.linspace(-90, 90, 181)

array([-90., -89., -88., -87., -86., -85., -84., -83., -82., -81., -80.,
       -79., -78., -77., -76., -75., -74., -73., -72., -71., -70., -69.,
       -68., -67., -66., -65., -64., -63., -62., -61., -60., -59., -58.,
       -57., -56., -55., -54., -53., -52., -51., -50., -49., -48., -47.,
       -46., -45., -44., -43., -42., -41., -40., -39., -38., -37., -36.,
       -35., -34., -33., -32., -31., -30., -29., -28., -27., -26., -25.,
       -24., -23., -22., -21., -20., -19., -18., -17., -16., -15., -14.,
       -13., -12., -11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,
        -2.,  -1.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,
         9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,
        20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
        31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,
        42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,
        53.,  54.,  55.,  56.,  57.,  58.,  59.,  6

**2.2** Convert the following list of lists into a 2D numpy array

In [79]:
data_list = np.array([[3,4],[4,5]])
print(data_list)

[[3 4]
 [4 5]]


**2.3** Stack the following 1D arrays vertically into a single 2D array.

In [7]:
A = np.array([1,1,1,1])
B = np.array([2,2,2,2])
C = np.stack((A, B), axis = 0)
print(np.stack((A, B), axis = 0))
print(C)
print(C[0][1])

[[1 1 1 1]
 [2 2 2 2]]
[[1 1 1 1]
 [2 2 2 2]]
1


**2.4** Compute the unique values of the following array. Note that simply writing them out is not sufficient.

In [81]:
np.random.seed(1)
A = np.random.randint(1,10,10000)
print(np.unique(A))

[1 2 3 4 5 6 7 8 9]


**2.5** Reshape the defined 1D array A into a 2D array B. The size of each dimension of B should be defined as the square root of the total size of A. Remember that the computed dimensions of B need to be integers.

In [82]:
A = np.arange(100)
print(np.reshape(A, (10, 10)))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


## 3. Mathematics  (15 points)

**3.1** Create a function that uses a for loop to compute the sum of all the elements in the array A. Use %timeit to compute the time it takes to run the defined function. 

In [83]:
np.random.seed(1)
A = np.random.randn(1000)

def total(x):
    y = 0
    for i in x:
        y += i
    return(y)

%timeit total(A)

218 µs ± 5.21 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**3.2** Now use the function np.sum() to compute the sum of the defined array A. Use %timeit to compute the time it takes to run the operation. Using the Markdown language in the additional cell below, compare the timing results with those from exercise **3.1**.

In [84]:
np.random.seed(1)
A = np.random.randn(1000)

%timeit np.sum(A)

5.24 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


**3.3** Compute the element-wise addition of the defined arrays A and B. The results should be assigned to a variable C. Then compute and print the mean, sum, standard deviation, maximum, minimum, and median of the resulting array. 

In [106]:
np.random.seed(1)
A = np.random.randn(1000)
print(A)
B = np.random.randn(1000)
C = A + B
print("The mean is:", np.mean(C))
print("The sum is:", np.sum(C))
print("The standard deviation is:", np.std(C))
print("The maximum is:", np.max(C))
print("The minimum is:", np.min(C))
print("The median is:", np.median(C))

[ 1.62434536e+00 -6.11756414e-01 -5.28171752e-01 -1.07296862e+00
  8.65407629e-01 -2.30153870e+00  1.74481176e+00 -7.61206901e-01
  3.19039096e-01 -2.49370375e-01  1.46210794e+00 -2.06014071e+00
 -3.22417204e-01 -3.84054355e-01  1.13376944e+00 -1.09989127e+00
 -1.72428208e-01 -8.77858418e-01  4.22137467e-02  5.82815214e-01
 -1.10061918e+00  1.14472371e+00  9.01590721e-01  5.02494339e-01
  9.00855949e-01 -6.83727859e-01 -1.22890226e-01 -9.35769434e-01
 -2.67888080e-01  5.30355467e-01 -6.91660752e-01 -3.96753527e-01
 -6.87172700e-01 -8.45205641e-01 -6.71246131e-01 -1.26645989e-02
 -1.11731035e+00  2.34415698e-01  1.65980218e+00  7.42044161e-01
 -1.91835552e-01 -8.87628964e-01 -7.47158294e-01  1.69245460e+00
  5.08077548e-02 -6.36995647e-01  1.90915485e-01  2.10025514e+00
  1.20158952e-01  6.17203110e-01  3.00170320e-01 -3.52249846e-01
 -1.14251820e+00 -3.49342722e-01 -2.08894233e-01  5.86623191e-01
  8.38983414e-01  9.31102081e-01  2.85587325e-01  8.85141164e-01
 -7.54397941e-01  1.25286

**3.4** Compute the element-wise remainder after dividing the defined array B by A. 

In [111]:
np.random.seed(1)
A = np.random.randint(1,10,10)
B = np.random.randint(1,10,10)
print(B % A)

[0 3 5 0 0 0 0 2 2 1]


**3.5** Let $f = x/(1 + x^2) + ln(x) - cos(x)$. After creating an evenly spaced array $x$ between 1 and 11 with 101 elements, compute $f$. To finish, print the mean and standard deviation of the computed array f.

In [87]:
A = np.linspace(1, 11, 101)
f = A/(1 + A**2) + np.log(A) - np.cos(A)
print("The mean of the array f is: ")
print(np.mean(f))
print("The standard deviation of the array f is: ")
print(np.std(f))

The mean of the array f is: 
2.019169709739239
The standard deviation of the array f is: 
0.8439365059793181


## 4. Indexing and slicing  (15 points)

**4.1** Replace the values of indices 5,1,2 in A with indices 8,8,2 in B. Note that replacing the values one by one (i.e., A[5] = B[8], A[1] = B[8]...) is not an adequate answer.

In [4]:
import numpy as np
A = np.linspace(0,10,11)
B = A[::-1]
A[[5, 1, 2]] = B[[8, 8, 2]]
print(A)

print(type(A))

[ 0.  2.  8.  3.  4.  2.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


**4.2** Subsample the given 2D array A every 5 elements to create a vector b. Remember to flatten A to a 1D array before subsampling. 

In [10]:
A = np.arange(25).reshape(5,5)
print(A)
A = A.ravel()
print(A[ : : 5])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  5 10 15 20]


**4.3** Given the array `lons` defined below, use a Boolean mask to determine the pixels that are above or equal to -60$^o$ and below or equal to 60$^o$. Then compute and print the number of elements that satisfy this condition [Hint: sum the Boolean mask]. 

In [90]:
minlon = -180.0
maxlon = 180.0
lons = np.linspace(minlon,maxlon,(maxlon-minlon)/0.25+1)
m1 = lons >= -60
m2 = lons <= 60
mask = m1 & m2
ans = lons[mask]
print(ans)
print("The number of elements that satisfy this condition is: ")
print(len(ans))

[-60.   -59.75 -59.5  -59.25 -59.   -58.75 -58.5  -58.25 -58.   -57.75
 -57.5  -57.25 -57.   -56.75 -56.5  -56.25 -56.   -55.75 -55.5  -55.25
 -55.   -54.75 -54.5  -54.25 -54.   -53.75 -53.5  -53.25 -53.   -52.75
 -52.5  -52.25 -52.   -51.75 -51.5  -51.25 -51.   -50.75 -50.5  -50.25
 -50.   -49.75 -49.5  -49.25 -49.   -48.75 -48.5  -48.25 -48.   -47.75
 -47.5  -47.25 -47.   -46.75 -46.5  -46.25 -46.   -45.75 -45.5  -45.25
 -45.   -44.75 -44.5  -44.25 -44.   -43.75 -43.5  -43.25 -43.   -42.75
 -42.5  -42.25 -42.   -41.75 -41.5  -41.25 -41.   -40.75 -40.5  -40.25
 -40.   -39.75 -39.5  -39.25 -39.   -38.75 -38.5  -38.25 -38.   -37.75
 -37.5  -37.25 -37.   -36.75 -36.5  -36.25 -36.   -35.75 -35.5  -35.25
 -35.   -34.75 -34.5  -34.25 -34.   -33.75 -33.5  -33.25 -33.   -32.75
 -32.5  -32.25 -32.   -31.75 -31.5  -31.25 -31.   -30.75 -30.5  -30.25
 -30.   -29.75 -29.5  -29.25 -29.   -28.75 -28.5  -28.25 -28.   -27.75
 -27.5  -27.25 -27.   -26.75 -26.5  -26.25 -26.   -25.75 -25.5  -25.25
 -25. 

**4.4** Given the mask computed above, use the function np.where() to determine the indices of the array A where the mask is True. Print the index of the first element that meets that condition. 

In [91]:
hhh = np.where(mask)
print(hhh[0][0])

480


**4.5** Create a checkerboard 4x4 array (zeros and ones). Note that writing the checkerboard array out manually (i.e., A = np.array([[1,0,1,0],[0,1,0,1],...])) is not an adequate answer. You will want to first initialize a 4x4 array of zeros and then fill in with ones where necessary using slicing. 

In [9]:
sasa = np.zeros((4,4))
print(sasa)
sasa[0::2, 0::2] = 1
print(sasa)
sasa[1::2, 1::2] = 1
print(sasa)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]


## 5. Dates (15 points)

**5.1** Import the module datetime.

In [93]:
import datetime

**5.2** Construct an instance of the class datetime.datetime for January, 30th, 2019 at 00:35. Print the resulting variable `date`.

In [94]:
date = datetime.datetime(2019, 1, 30, 0, 35, 0)
print(date)

2019-01-30 00:35:00


**5.3** Assemble a list of dates consisting of all 3 hourly timestamps of March, 1995. Assume that the first time stamp is March 1st, 2019 at 00:00. Convert the resulting list into an array. Print the 40th element and the size of the resulting array.

In [95]:
import datetime
import numpy as np

idate = datetime.datetime(2019, 3, 1, 0, 0, 0)
fdate = datetime.datetime(2019, 3, 31, 23, 59, 59)
dt = datetime.timedelta(hours = 3)
date = idate
dates = []

while date <= fdate:
    date = date + dt
    dates.append(date)

datetimearray = np.array(dates)
print("The 40th element of the resulting array is: ")
print(datetimearray[39])
print("The size of the resulting array is: ")
print(datetimearray.size)

The 40th element of the resulting array is: 
2019-03-06 00:00:00
The size of the resulting array is: 
248


**5.4** Given the array `dates` defined above, use a Boolean mask to compute all dates that are after March 4th, 2019 at 3:00 am and before March 10th, 2019 at 6:00 pm. Create a new dates array by subsetting the original dates array with the mask. Print the resulting array.

In [96]:
m1 = datetimearray >= datetime.datetime(2019, 3, 4, 3, 0, 0)
m2 = datetimearray <= datetime.datetime(2019, 3, 10, 18, 0, 0)
mask = m1 & m2
print(datetimearray[mask])

[datetime.datetime(2019, 3, 4, 3, 0) datetime.datetime(2019, 3, 4, 6, 0)
 datetime.datetime(2019, 3, 4, 9, 0) datetime.datetime(2019, 3, 4, 12, 0)
 datetime.datetime(2019, 3, 4, 15, 0) datetime.datetime(2019, 3, 4, 18, 0)
 datetime.datetime(2019, 3, 4, 21, 0) datetime.datetime(2019, 3, 5, 0, 0)
 datetime.datetime(2019, 3, 5, 3, 0) datetime.datetime(2019, 3, 5, 6, 0)
 datetime.datetime(2019, 3, 5, 9, 0) datetime.datetime(2019, 3, 5, 12, 0)
 datetime.datetime(2019, 3, 5, 15, 0) datetime.datetime(2019, 3, 5, 18, 0)
 datetime.datetime(2019, 3, 5, 21, 0) datetime.datetime(2019, 3, 6, 0, 0)
 datetime.datetime(2019, 3, 6, 3, 0) datetime.datetime(2019, 3, 6, 6, 0)
 datetime.datetime(2019, 3, 6, 9, 0) datetime.datetime(2019, 3, 6, 12, 0)
 datetime.datetime(2019, 3, 6, 15, 0) datetime.datetime(2019, 3, 6, 18, 0)
 datetime.datetime(2019, 3, 6, 21, 0) datetime.datetime(2019, 3, 7, 0, 0)
 datetime.datetime(2019, 3, 7, 3, 0) datetime.datetime(2019, 3, 7, 6, 0)
 datetime.datetime(2019, 3, 7, 9, 0) da

## 6. Distance between two points on Earth (15 points)

The central angle, $\Delta \sigma$, between two different points on the Earth is given by:

$\Delta \sigma  = \arccos(\sin\phi_1\sin\phi_2 + \cos\phi_1\cos\phi_2\cos(\lambda_2 - \lambda_1))$

where $\lambda_1$ and $\lambda_2$ are the longitudes and $\phi_1$ and $\phi_2$ are the latitudes in radians of points 1 and 2.

The distance between the two points in km can then be computed via the arc length by assuming that $R_e = 6371$ km:

$d = R_e\Delta \sigma$

**6.1** Create a function named `compute_distance` that computes the arc length between two points on Earth in km. The function input parameters should be lat1, lon1, lat2, and lon2. Remember that the latitude and longitudes values need to be in radians.

In [97]:
import numpy as np

def compute_distance(lat1, lon1, lat2, lon2):
    delta = np.arccos(np.sin(lat1*np.pi/180)*np.sin(lat2*np.pi/180)+np.cos(lat1*np.pi/180)*np.cos(lat2*np.pi/180)*np.cos(lon2*np.pi/180-lon1*np.pi/180))
    print(6371 * delta)

**6.2** Use the function defined above to compute the distance between Durham, NC and Chicago, IL. The coordinates of Durham, NC are 35.9940$^o$ N and 78.8986$^o$ W. The coordinates of Chicago, IL are 41.8781$^o$ N and 87.6298$^o$ W. Print the computed distance.

In [98]:
lat1 = 35.9940
lon1 = 78.8986
lat2 = 41.8781
lon2 = 87.6298
compute_distance(lat1, lon1, lat2, lon2)

998.2333233016485


**6.3** Create a class called point that is initialized using two variables `lat` and `lon`. Then add the `compute_distance` function defined previously as a method. [Hint: See the example of creating and using classes shown in Lecture 2]

In [99]:
import numpy as np

class point():
    def __init__(self, lat, lon):
        self.lat = lat
        self.lon = lon
    
    def compute_distance(self, lat2, lon2):
        self.distance = 6371 * np.arccos(np.sin(self.lat*np.pi/180)*np.sin(lat2*np.pi/180)+np.cos(self.lat*np.pi/180)*np.cos(lat2*np.pi/180)*np.cos(lon2*np.pi/180-self.lon*np.pi/180))

**6.4** Instantiate the class `point` for Durham using the lat and lon values defined in **6.2**.

In [100]:
lat = 35.9940
lon = 78.8986
estdistance = point(lat, lon)

**6.5** Compute the distance between Durham and Chicago using the object defined in the previous exercise. Note that this will give the same result as **6.2**, however, it will involve using classes instead of a single function.

In [101]:
estdistance.compute_distance(41.8781, 87.6298)
print(estdistance.distance)

998.2333233016485


## 7. Parsing filepaths (15 points)

The directory `/shared_space/data/NED` contains the entire database of the National Elevation Dataset (NED) which provides maps of elevation over the entire Contiguous United States at a 1 arcsec (~30 meter) spatial resolution. Given the large size of the data, the entire dataset is split into 1$^o$ x 1$^o$ arcdegree boxes. Each file in the directory looks similar to "dem_lat3637_lon-105-104.tif". This file contains the elevation information for the region between the latitudes of 36.0 and 37.0 and the longitudes of -105.0 and -104.0. 

**7.1** Import the module glob

In [4]:
import glob

**7.2** Use the function glob.glob() to make a list of all the files that end with .tif in the directory defined above. Print the resulting list. [Hint: Use *.tif to only extract the geotiff files]

In [5]:
import os

print(os.getcwd())
os.chdir('/shared_space/data/NED')
print(os.getcwd())

file = glob.glob('*.tif')
print("The resulting list is: ")
print(file)

/home/jovyan/work/ESDA_zy


FileNotFoundError: [Errno 2] No such file or directory: '/shared_space/data/NED'

**7.3** Print the number of files in the computed list.

In [6]:
print(len(file))

NameError: name 'file' is not defined

**7.4** Subset the previously computed list to extract only files that fall within the bounding box of minlat = 30.0, maxlat = 35.0, minlon = -85.0, and maxlon = -80.0. Print the resulting list and the number of elements in the list. [Hint: You will need to use a for loop, the split() function of strings, slicing of strings, and logical operators to complete this exercise].

In [7]:
minlat = 30.0
maxlat = 35.0
minlon = 80.0
maxlon = 85.0

minlatt = []
maxlatt = []
maxlonn = []
minlonn = []
filefinal = []

for i, item in enumerate(file):
    test1 = item.split('lat')[1].split('_lon')[0]
    test2 = item.split('lat')[1].split('_lon')[1].split('.tif')[0].split('-')
    minlatt.append(test1[0:2])
    maxlatt.append(test1[2:4])
    maxlonn.append(test2[1])
    minlonn.append(test2[2])
    minlatt = list(map(int, minlatt))
    maxlatt = list(map(int, maxlatt))
    maxlonn = list(map(int, maxlonn))
    minlonn = list(map(int, minlonn))
    if minlatt[i] >= minlat and maxlatt[i] <= maxlat and maxlonn[i] <= maxlon and minlonn[i] >= minlon:
        filefinal.append(file[i])

print("The list of files fall within the bounding box is: ")
print(filefinal)
print("\nThe number of elements in the list is: ")
print(len(filefinal))

NameError: name 'file' is not defined